### PR TITLE
initial setup

### PR DESCRIPTION
**Pull request by jakub-gosciniak**

### CODE REVIEW

**Comment by Polo11121** [comment]
: DDDD

**Review by mateusz0612 — APPROVED** [review]
LGTM!

**Review by mateusz0612 — APPROVED** [review]

**Comment by Polo11121** [comment]
lNGTM : (

**Review by MateuszLisowski — APPROVED** [review]

**Review by MateuszLisowski — CHANGES_REQUESTED** [review]
Test

**Review by MateuszLisowski — APPROVED** [review]

**Review by mateusz0612 — APPROVED** [review]

**Review by mateusz0612 — APPROVED** [review]

**Pull request merged**
